import { describe, expect, it } from "vitest";
import { modelPrompt } from "./context.ts";
import type { TurnContext } from "./store.ts";

describe("modelPrompt", () => {
	it("maps people and other agents to attributed user messages", () => {
		const prompt = modelPrompt(context());

		expect(prompt.system).toContain(
			"You are Host Agent (@host-agent), an agent in pod Release of workspace Suga",
		);
		expect(prompt.system).toContain("Check facts carefully.");
		// The history, then one trailing instruction with everything that varies
		// between turns, so the prefix the provider caches never changes shape.
		expect(prompt.messages.slice(0, -1)).toEqual([
			{ role: "user", content: "Sam (@sam): Check the release" },
			{ role: "assistant", content: "I am checking it." },
			{ role: "user", content: "Reviewer (@reviewer) (agent): Migration is present." },
		]);
		const instruction = prompt.messages.at(-1);
		expect(instruction?.role).toBe("user");
		expect(instruction?.content).toContain(
			"In the thread now: Sam (@sam, person), Host Agent (@host-agent, agent), Reviewer (@reviewer, agent).",
		);
		expect(instruction?.content).toContain(
			"It is your turn as the agent this thread was addressed to.",
		);
		expect(prompt.system).not.toContain("Sam (@sam, person)");
	});

	it("lists potential collaborators, and tells one why its thread exists", () => {
		const asking = context();
		asking.crew = [
			{
				id: "0199a3a0-0000-7000-8000-000000000005",
				name: "Reviewer",
				handle: "reviewer",
				description: "Checks facts.",
			},
			{
				id: "0199a3a0-0000-7000-8000-000000000009",
				name: "Scout",
				handle: "scout",
				description: null,
			},
		];
		const instruction = () => modelPrompt(asking).messages.at(-1)?.content ?? "";
		expect(instruction()).toContain(
			"Other agents in this pod, and what each one knows:\n- Reviewer (@reviewer): Checks facts.\n- Scout (@scout)",
		);
		expect(instruction()).toContain(
			"Use the collaborate tool when you need another agent's answer",
		);
		expect(instruction()).not.toContain("callout tool");
		expect(modelPrompt(context()).messages.at(-1)?.content).not.toContain("collaborate tool");

		const collaboration = context();
		collaboration.thread.parentThreadId = "0199a3a0-0000-7000-8000-000000000010";
		expect(modelPrompt(collaboration).system).toContain("Another agent opened this thread");
	});

	it("names the built-in tools on offer, and says nothing about them when there are none", () => {
		const withTools = modelPrompt(context(), { builtInTools: ["web_fetch"] }).messages.at(-1);
		expect(withTools?.content).toContain("Built-in tools you can call: web_fetch.");
		expect(withTools?.content).toContain("name its URL");

		const without = modelPrompt(context()).messages.at(-1);
		expect(without?.content).not.toContain("Built-in tools");
	});

	it("names the connection tools on offer and how their names are made", () => {
		const prompt = modelPrompt(context(), { connectionTools: ["wiki__search_pages"] }).messages.at(
			-1,
		);
		expect(prompt?.content).toContain("connections you can call: wiki__search_pages.");
		expect(prompt?.content).toContain("double underscore");
	});

	it("writes the agent's own tool calls into its history as one line each, not the whole output", () => {
		const input = context();
		const own = input.messages[1];
		if (!own) {
			throw new Error("Context fixture has no assistant message");
		}
		const page = "word ".repeat(400);
		input.messages[1] = {
			...own,
			content: "Looking. Found it.",
			parts: [
				{ type: "text", text: "Looking." },
				{
					type: "tool_call",
					id: "0199a3a0-0000-7000-8000-000000000020",
					tool: "web_fetch",
					input: { url: "https://example.com" },
					output: { title: "Example Domain", text: page },
					status: "completed",
					error: null,
					mutating: false,
					atOffset: 8,
					startedAt: "2026-09-14T00:00:00.000Z",
					finishedAt: "2026-09-14T00:00:01.000Z",
				},
				{
					type: "tool_call",
					id: "0199a3a0-0000-7000-8000-000000000021",
					tool: "web_search",
					input: { query: "release" },
					output: null,
					status: "failed",
					error: "No search provider",
					mutating: false,
					atOffset: 8,
					startedAt: "2026-09-14T00:00:00.000Z",
					finishedAt: "2026-09-14T00:00:01.000Z",
				},
				{ type: "text", text: " Found it." },
			],
		};

		const prompt = modelPrompt(input);
		const authored = prompt.messages[1];
		const history = prompt.messages[2]?.content ?? "";

		expect(authored).toEqual({ role: "assistant", content: "Looking. Found it." });
		expect(history).toContain("Generated by the application, not authored");
		expect(history).toContain('[Used web_fetch with {"url":"https://example.com"}: ');
		expect(history).toContain("… (");
		expect(history).not.toContain(page);
		expect(history).toContain(
			'[Used web_search with {"query":"release"}; it failed: No search provider]',
		);
	});

	it("excludes incomplete assistant output", () => {
		const input = context();
		const assistantMessage = input.messages[1];
		if (!assistantMessage) {
			throw new Error("Context fixture has no assistant message");
		}
		input.messages.push(
			...(["failed", "cancelled", "streaming"] as const).map((status, index) => ({
				...assistantMessage,
				id: `0199a3a0-0000-7000-8000-00000000001${index}`,
				status,
				content: `${status} partial answer`,
				parts: [{ type: "text" as const, text: `${status} partial answer` }],
			})),
		);

		const prompt = modelPrompt(input);

		expect(prompt.system).toContain(
			"Platform event log messages are application-generated records",
		);
		expect(prompt.messages).not.toContainEqual(
			expect.objectContaining({ content: expect.stringContaining("partial answer") }),
		);
	});
});

function context(): TurnContext {
	return {
		thread: {
			id: "0199a3a0-0000-7000-8000-000000000001",
			workspaceId: "0199a3a0-0000-7000-8000-000000000002",
			title: "Check the release",
			parentThreadId: null,
		},
		agent: {
			id: "0199a3a0-0000-7000-8000-000000000003",
			podId: "0199a3a0-0000-7000-8000-000000000009",
			name: "Host Agent",
			handle: "host-agent",
			model: "claude-sonnet-4-20250514",
			prompt: "Check facts carefully.",
			disabledTools: [],
		},
		reason: "default",
		routing: { facilitator: false },
		podName: "Release",
		workspaceName: "Suga",
		crew: [],
		participants: [
			{
				kind: "person",
				id: "0199a3a0-0000-7000-8000-000000000004",
				name: "Sam",
				email: "sam@example.com",
				handle: "sam",
				image: null,
			},
			{
				kind: "agent",
				id: "0199a3a0-0000-7000-8000-000000000003",
				name: "Host Agent",
				handle: "host-agent",
				hue: 150,
				face: "bar",
			},
			{
				kind: "agent",
				id: "0199a3a0-0000-7000-8000-000000000005",
				name: "Reviewer",
				handle: "reviewer",
				hue: 40,
				face: "dots",
			},
		],
		messages: [
			{
				id: "0199a3a0-0000-7000-8000-000000000006",
				threadId: "0199a3a0-0000-7000-8000-000000000001",
				author: {
					kind: "person",
					id: "0199a3a0-0000-7000-8000-000000000004",
					name: "Sam",
					email: "sam@example.com",
					handle: "sam",
					image: null,
				},
				kind: "text",
				status: "complete",
				parts: [{ type: "text", text: "Check the release" }],
				content: "Check the release",
				createdAt: "2026-09-10T04:00:00.000Z",
			},
			{
				id: "0199a3a0-0000-7000-8000-000000000007",
				threadId: "0199a3a0-0000-7000-8000-000000000001",
				author: {
					kind: "agent",
					id: "0199a3a0-0000-7000-8000-000000000003",
					name: "Host Agent",
					handle: "host-agent",
					hue: 150,
					face: "bar",
				},
				kind: "text",
				status: "complete",
				parts: [{ type: "text", text: "I am checking it." }],
				content: "I am checking it.",
				createdAt: "2026-09-10T04:01:00.000Z",
			},
			{
				id: "0199a3a0-0000-7000-8000-000000000008",
				threadId: "0199a3a0-0000-7000-8000-000000000001",
				author: {
					kind: "agent",
					id: "0199a3a0-0000-7000-8000-000000000005",
					name: "Reviewer",
					handle: "reviewer",
					hue: 40,
					face: "dots",
				},
				kind: "text",
				status: "complete",
				parts: [{ type: "text", text: "Migration is present." }],
				content: "Migration is present.",
				createdAt: "2026-09-10T04:02:00.000Z",
			},
		],
	};
}
